---

- name: Kubernetes Apps | Permitir todo el tr치fico de una aplicacion desde otros namespace | Listar plantillas de politica ingress 
  set_fact:
    allow_ingress_trafico_from_all_ns_a_pod_templates:
      - {file: allow-ingress-trafico-from-all-ns-a-pod.yaml, type: networkpolicy, name: allow-ingress-trafico-from-all-ns-a-pod}
  when:
  - networkpolicies.ingress.enabled|default(false)
  - networkpolicies.ingress.allow_all_trafico_otros_ns_a_pod.enabled|default(false)

- name: "Kubernetes Apps | Permitir todo el tr치fico de una aplicacion desde otros namespace | Crear directorio para manifiesto (en {{ groups['kube-master'][0] }})"
  file:
    path: "{{ networkpolicies_ingress_config_dir_temp }}"
    group: "{{ usuario_networkpolicies_group }}"
    state: directory
    owner: kube
    recurse: yes
    mode: 0700
  run_once: yes
  when: 
    - inventory_hostname == groups['kube-master'][0] 
    - networkpolicies.ingress.enabled|default(false)
    - networkpolicies.ingress.allow_all_trafico_otros_ns_a_pod.enabled|default(false)
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: Kubernetes Apps | Permitir todo el tr치fico de una aplicacion desde otros namespace | Copiar plantilla network policies ingress
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ networkpolicies_ingress_config_dir_temp }}/{{ item.file }}"
  with_items: "{{ allow_ingress_trafico_from_all_ns_a_pod_templates }}"
  register: manifests
  when:
    - inventory_hostname == groups['kube-master'][0]
    - networkpolicies.ingress.enabled|default(false)
    - networkpolicies.ingress.allow_all_trafico_otros_ns_a_pod.enabled|default(false)

- name: Kubernetes Apps | Permitir todo el tr치fico de una aplicacion desde otros namespace | Ejecutar politica
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ networkpolicies.ingress.allow_all_trafico_otros_ns_a_pod.namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ networkpolicies_ingress_config_dir_temp }}/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ manifests.results }}"
  when:
    - inventory_hostname == groups['kube-master'][0]
    - networkpolicies.ingress.enabled|default(false)
    - networkpolicies.ingress.allow_all_trafico_otros_ns_a_pod.enabled|default(false)
    - item.item.name == "allow-ingress-trafico-from-all-ns-a-pod"
    - not item is skipped